//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO_SOLICITADO
    {
        public string ID_PRESTAMO { get; set; }
        public string TIPO_ACTIVO { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> CANTIDADAPROBADA { get; set; }
        public int TIPOS_ACTIVOSID { get; set; }
    
        public virtual PRESTAMO PRESTAMO { get; set; }
        public virtual TIPOS_ACTIVOS TIPOS_ACTIVOS { get; set; }
    }
}
