//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrestamosEntities : DbContext
    {
        public PrestamosEntities()
            : base("name=PrestamosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EQUIPO_SOLICITADO> EQUIPO_SOLICITADO { get; set; }
        public virtual DbSet<PRESTAMO> PRESTAMOS { get; set; }
        public virtual DbSet<ACTIVO> ACTIVOS { get; set; }
        public virtual DbSet<TIPOS_ACTIVOS> TIPOS_ACTIVOS { get; set; }
        public virtual DbSet<ESTADOS_ACTIVOS> ESTADOS_ACTIVOS { get; set; }
        public virtual DbSet<V_ANFITRIONA> V_ANFITRIONA { get; set; }
        public virtual DbSet<V_ESTACION> V_ESTACION { get; set; }
        public virtual DbSet<V_MONEDA> V_MONEDA { get; set; }
        public virtual DbSet<V_PROVEEDOR> V_PROVEEDOR { get; set; }
        public virtual DbSet<V_TIPO_CAMBIO> V_TIPO_CAMBIO { get; set; }
        public virtual DbSet<CENTROS_DE_COSTOS> CENTROS_DE_COSTOS { get; set; }
        public virtual DbSet<TIPOS_TRANSACCIONES> TIPOS_TRANSACCIONES { get; set; }
        public virtual DbSet<TRANSACCION> TRANSACCIONES { get; set; }
        public virtual DbSet<ActivosUser> ActivosUsers { get; set; }
        public virtual DbSet<V_COURSES> V_COURSES { get; set; }
        public virtual DbSet<V_EMPLEADOS> V_EMPLEADOS { get; set; }
    }
}
