-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 24/6/2016 4:52:58 p. m.
-- Generated from EDMX file: C:\Users\Fabo\Documents\UCR\I Semestre 2016\Inge II\ProyectoActivosPrestamos\Activos-PrestamosOET\Models\PrestamosOET.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

 ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO" DROP CONSTRAINT "FK_A_PRESTAMOS" CASCADE;

 ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO" DROP CONSTRAINT "FK_ACTIVOPRESTAMO_ACTIVO" CASCADE;

 ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO" DROP CONSTRAINT "FK_ACTIVOPRESTAMO_PRESTAMO" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_TIPO_ACTIVOACTIVO" CASCADE;

 ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO" DROP CONSTRAINT "FK_TIPOS_ACTIVOSEQUIPO_SOLICITADO" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_ESTADO_ACTIVOACTIVO" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_V_MONEDAACTIVO" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_CENTRO_DE_COSTOACTIVO" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_V_PROVEEDORACTIVO" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_V_ANFITRIONAACTIVO" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_TIPO_TRANSACCIONACTIVO" CASCADE;

 ALTER TABLE "ACTIVOS"."TRANSACCIONES" DROP CONSTRAINT "FK_ACTIVOTRANSACCION" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_V_ESTACIONACTIVO" CASCADE;

 ALTER TABLE "ACTIVOS"."PRESTAMOS" DROP CONSTRAINT "FK_ActivosUserPRESTAMO" CASCADE;

 ALTER TABLE "ACTIVOS"."PRESTAMOS" DROP CONSTRAINT "FK_ActivosUserPRESTAMO1" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_V_EMPLEADOSACTIVO" CASCADE;

 ALTER TABLE "ACTIVOS"."PRESTAMOS" DROP CONSTRAINT "FK_PRESTAMOV_COURSES" CASCADE;

 ALTER TABLE "ACTIVOS"."TRANSACCIONES" DROP CONSTRAINT "FK_V_EMPLEADOSTRANSACCION" CASCADE;
-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

 DROP TABLE "ACTIVOS"."EQUIPO_SOLICITADO";

 DROP TABLE "ACTIVOS"."PRESTAMOS";

-- DROP TABLE "ACTIVOS"."ACTIVOS";

-- DROP TABLE "ACTIVOS"."TIPOS_ACTIVOS";

-- DROP TABLE "ACTIVOS"."ESTADOS_ACTIVOS";

-- DROP TABLE "ACTIVOS"."V_ANFITRIONA";

-- DROP TABLE "ACTIVOS"."V_ESTACION";

-- DROP TABLE "ACTIVOS"."V_MONEDA";

-- DROP TABLE "ACTIVOS"."V_PROVEEDOR";

-- DROP TABLE "ACTIVOS"."V_TIPO_CAMBIO";

-- DROP TABLE "ACTIVOS"."CENTROS_DE_COSTOS";

-- DROP TABLE "ACTIVOS"."TIPOS_TRANSACCIONES";

 DROP TABLE "ACTIVOS"."TRANSACCIONES";

-- DROP TABLE "ACTIVOS"."ActivosUsers";

 DROP TABLE "ACTIVOS"."V_COURSES";

-- DROP TABLE "ACTIVOS"."V_EMPLEADOS";

 DROP TABLE "ACTIVOS"."ACTIVOPRESTAMO";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'EQUIPO_SOLICITADO'
CREATE TABLE "ACTIVOS"."EQUIPO_SOLICITADO" (
   "ID_PRESTAMO" VARCHAR2(25 CHAR) NOT NULL,
   "TIPO_ACTIVO" VARCHAR2(50 CHAR) NOT NULL,
   "CANTIDAD" NUMBER(38) NOT NULL,
   "CANTIDADAPROBADA" NUMBER(38) ,
   "TIPOS_ACTIVOSID" NUMBER(10) NOT NULL
);

-- Creating table 'PRESTAMOS'
CREATE TABLE "ACTIVOS"."PRESTAMOS" (
   "ID" VARCHAR2(25 CHAR) NOT NULL,
   "NUMERO_BOLETA" NUMBER(19) ,
   "MOTIVO" VARCHAR2(250 CHAR) ,
   "FECHA_SOLICITUD" DATE NOT NULL,
   "FECHA_RETIRO" DATE NOT NULL,
   "PERIODO_USO" NUMBER(10) NOT NULL,
   "SOFTWARE_REQUERIDO" VARCHAR2(250 CHAR) ,
   "OBSERVACIONES_SOLICITANTE" VARCHAR2(250 CHAR) ,
   "OBSERVACIONES_APROBADO" VARCHAR2(250 CHAR) ,
   "OBSERVACIONES_RECIBIDO" VARCHAR2(250 CHAR) ,
   "SIGLA_CURSO" CHAR(8 CHAR) ,
   "Estado" NUMBER(5) NOT NULL,
   "USUARIO_SOLICITA" NVARCHAR2(128) NOT NULL,
   "USUARIO_APRUEBA" NVARCHAR2(128) ,
   "V_COURSESCOURSES" NUMBER(10) NOT NULL
);

-- Creating table 'ACTIVOS'
CREATE TABLE "ACTIVOS"."ACTIVOS" (
   "ID" NVARCHAR2(256) NOT NULL,
   "NUMERO_SERIE" NVARCHAR2(64) ,
   "FECHA_COMPRA" DATE NOT NULL,
   "INICIO_SERVICIO" DATE ,
   "FECHA_INGRESO" DATE NOT NULL,
   "FABRICANTE" NVARCHAR2(64) NOT NULL,
   "PRECIO" NUMBER(38) NOT NULL,
   "DESCRIPCION" NVARCHAR2(256) NOT NULL,
   "EXENTO" NUMBER(1) NOT NULL,
   "PRESTABLE" NUMBER(1) NOT NULL,
   "TIPO_CAPITAL" NUMBER(1) NOT NULL,
   "INGRESADO_POR" NVARCHAR2(128) NOT NULL,
   "NUMERO_DOCUMENTO" NVARCHAR2(32) NOT NULL,
   "NUMERO_LOTE" NVARCHAR2(32) ,
   "TIPO_TRANSACCIONID" NUMBER(10) NOT NULL,
   "ESTADO_ACTIVOID" NUMBER(10) NOT NULL,
   "TIPO_ACTIVOID" NUMBER(10) NOT NULL,
   "COMENTARIO" NVARCHAR2(256) ,
   "DESECHADO" NUMBER(1) NOT NULL,
   "MODELO" NVARCHAR2(128) ,
   "V_ESTACIONID" VARCHAR2(26 CHAR) ,
   "V_ANFITRIONAID" VARCHAR2(2 CHAR) NOT NULL,
   "V_PROVEEDORIDPROVEEDOR" VARCHAR2(50 CHAR) NOT NULL,
   "V_MONEDAID" VARCHAR2(26 CHAR) NOT NULL,
   "CENTRO_DE_COSTOId" NUMBER(10) ,
   "PLACA" NVARCHAR2(64) ,
   "ESTADO_PRESTADO" NUMBER(10) ,
   "V_EMPLEADOSIDEMPLEADO" VARCHAR2(30 CHAR) 
);

-- Creating table 'TIPOS_ACTIVOS'
CREATE TABLE "ACTIVOS"."TIPOS_ACTIVOS" (
   "ID" NUMBER(10) NOT NULL,
   "NOMBRE" NVARCHAR2(127) NOT NULL
);

-- Creating table 'ESTADOS_ACTIVOS'
CREATE TABLE "ACTIVOS"."ESTADOS_ACTIVOS" (
   "ID" NUMBER(10) NOT NULL,
   "NOMBRE" NVARCHAR2(30) NOT NULL
);

-- Creating table 'V_ANFITRIONA'
CREATE TABLE "ACTIVOS"."V_ANFITRIONA" (
   "ID" VARCHAR2(2 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(100 CHAR) NOT NULL,
   "SIGLAS" VARCHAR2(20 CHAR) NOT NULL,
   "MONEDA" VARCHAR2(26 CHAR) NOT NULL,
   "TIPOCAMBIO" VARCHAR2(10 CHAR) NOT NULL,
   "TIPOUSUARIO" NUMBER(38) NOT NULL,
   "TIPOCAMBIO_CONTA" VARCHAR2(10 CHAR) NOT NULL,
   "MONEDA_CONTA" VARCHAR2(26 CHAR) NOT NULL
);

-- Creating table 'V_ESTACION'
CREATE TABLE "ACTIVOS"."V_ESTACION" (
   "ID" VARCHAR2(26 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(100 CHAR) NOT NULL,
   "SIGLAS" VARCHAR2(20 CHAR) ,
   "RESERVABLE" VARCHAR2(1 CHAR) 
);

-- Creating table 'V_MONEDA'
CREATE TABLE "ACTIVOS"."V_MONEDA" (
   "ID" VARCHAR2(26 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(50 CHAR) ,
   "SIMBOLO" VARCHAR2(3 CHAR) 
);

-- Creating table 'V_PROVEEDOR'
CREATE TABLE "ACTIVOS"."V_PROVEEDOR" (
   "IDPROVEEDOR" VARCHAR2(50 CHAR) NOT NULL,
   "FECHAINGRESO" DATE NOT NULL,
   "NOMBRE" VARCHAR2(50 CHAR) NOT NULL,
   "RAZONSOCIAL" VARCHAR2(50 CHAR) ,
   "ESTADO" NUMBER(1) NOT NULL,
   "TIPOCEDULA" NUMBER(10) ,
   "CEDULA" VARCHAR2(50 CHAR) NOT NULL,
   "TELEFONO" VARCHAR2(50 CHAR) ,
   "FAX" VARCHAR2(50 CHAR) ,
   "SITIOWEB" VARCHAR2(100 CHAR) ,
   "CORREOELECTRONICO" VARCHAR2(50 CHAR) ,
   "LOCACION" NUMBER(1) NOT NULL,
   "IDPAIS" VARCHAR2(50 CHAR) ,
   "IDPROVINCIA" VARCHAR2(50 CHAR) ,
   "DIRECCION" VARCHAR2(255 CHAR) ,
   "IDFORMAPAGO" VARCHAR2(50 CHAR) ,
   "IDPLAZO" VARCHAR2(50 CHAR) ,
   "DESCUENTO" NUMBER(8,2) ,
   "INTERESMORA" NUMBER(8,2) ,
   "COMENTARIO" VARCHAR2(255 CHAR) ,
   "CONGELAR" NUMBER(1) ,
   "CREADO" DATE NOT NULL,
   "CREADOR" VARCHAR2(50 CHAR) NOT NULL,
   "MODIFICADO" DATE NOT NULL,
   "MODIFICADOR" VARCHAR2(50 CHAR) NOT NULL,
   "MONEDA" VARCHAR2(26 CHAR) ,
   "NOMBRE_CORTO" VARCHAR2(20 CHAR) 
);

-- Creating table 'V_TIPO_CAMBIO'
CREATE TABLE "ACTIVOS"."V_TIPO_CAMBIO" (
   "IDDOCUMENTO" VARCHAR2(26 CHAR) NOT NULL,
   "TIPOCAMBIO" NUMBER(38) NOT NULL
);

-- Creating table 'CENTROS_DE_COSTOS'
CREATE TABLE "ACTIVOS"."CENTROS_DE_COSTOS" (
   "Id" NUMBER(10) NOT NULL,
   "Nombre" NCLOB NOT NULL
);

-- Creating table 'TIPOS_TRANSACCIONES'
CREATE TABLE "ACTIVOS"."TIPOS_TRANSACCIONES" (
   "ID" NUMBER(10) NOT NULL,
   "NOMBRE" NVARCHAR2(30) NOT NULL
);

-- Creating table 'TRANSACCIONES'
CREATE TABLE "ACTIVOS"."TRANSACCIONES" (
   "ID" NUMBER(10) NOT NULL,
   "FECHA" TIMESTAMP NOT NULL,
   "RESPONSABLE" NVARCHAR2(63) NOT NULL,
   "ESTADO" NVARCHAR2(30) NOT NULL,
   "DESCRIPCION" NVARCHAR2(1024) NOT NULL,
   "ACTIVOID" NVARCHAR2(256) NOT NULL,
   "NUMERO_BOLETA" NUMBER(19) ,
   "FECHA_RETIRO" DATE ,
   "FECHA_DEVOLUCION" DATE ,
   "OBSERVACIONES_RECIBO" NVARCHAR2(250) ,
   "NOMBRE_SOLICITANTE" NVARCHAR2(100) ,
   "V_EMPLEADOSIDEMPLEADO" VARCHAR2(30 CHAR) 
);

-- Creating table 'ActivosUsers'
CREATE TABLE "ACTIVOS"."ActivosUsers" (
   "Id" NVARCHAR2(128) NOT NULL,
   "Email" NVARCHAR2(256) ,
   "EmailConfirmed" NUMBER(1) ,
   "PasswordHash" NVARCHAR2(256) ,
   "SecurityStamp" NVARCHAR2(256) ,
   "PhoneNumber" NVARCHAR2(256) ,
   "PhoneNumberConfirmed" NUMBER(1) ,
   "TwoFactorEnabled" NUMBER(1) ,
   "LockoutEndDateUtc" TIMESTAMP ,
   "LockoutEnabled" NUMBER(1) ,
   "AccessFailedCount" NUMBER(10) ,
   "UserName" NVARCHAR2(256) ,
   "Nombre" NVARCHAR2(100) ,
   "Apellidos" NVARCHAR2(100) ,
   "Cedula" NVARCHAR2(20) ,
   "EstacionID" VARCHAR2(26 CHAR) 
);

-- Creating table 'V_COURSES'
CREATE TABLE "ACTIVOS"."V_COURSES" (
   "COURSES" NUMBER(10) NOT NULL,
   "COURSES_CODE" VARCHAR2(100 CHAR) NOT NULL,
   "COURSE_NAME" VARCHAR2(1000 CHAR) ,
   "START_DATE" DATE ,
   "END_DATE" DATE 
);

-- Creating table 'V_EMPLEADOS'
CREATE TABLE "ACTIVOS"."V_EMPLEADOS" (
   "ESTACION_ID" VARCHAR2(30 CHAR) NOT NULL,
   "IDEMPLEADO" VARCHAR2(30 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(101 CHAR) ,
   "EMAIL" VARCHAR2(50 CHAR) ,
   "ESTADO" NUMBER(8,2) NOT NULL
);

-- Creating table 'ACTIVOPRESTAMO'
CREATE TABLE "ACTIVOS"."ACTIVOPRESTAMO" (
   "ACTIVOes_ID" NVARCHAR2(256) NOT NULL,
   "PRESTAMOes_ID" VARCHAR2(25 CHAR) NOT NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID_PRESTAMO", "TIPO_ACTIVO", "CANTIDAD"in table 'EQUIPO_SOLICITADO'
ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO"
ADD CONSTRAINT "PK_EQUIPO_SOLICITADO"
   PRIMARY KEY ("ID_PRESTAMO", "TIPO_ACTIVO", "CANTIDAD" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "PK_PRESTAMOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "PK_ACTIVOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TIPOS_ACTIVOS'
ALTER TABLE "ACTIVOS"."TIPOS_ACTIVOS"
ADD CONSTRAINT "PK_TIPOS_ACTIVOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'ESTADOS_ACTIVOS'
ALTER TABLE "ACTIVOS"."ESTADOS_ACTIVOS"
ADD CONSTRAINT "PK_ESTADOS_ACTIVOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'V_ANFITRIONA'
ALTER TABLE "ACTIVOS"."V_ANFITRIONA"
ADD CONSTRAINT "PK_V_ANFITRIONA"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'V_ESTACION'
ALTER TABLE "ACTIVOS"."V_ESTACION"
ADD CONSTRAINT "PK_V_ESTACION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'V_MONEDA'
ALTER TABLE "ACTIVOS"."V_MONEDA"
ADD CONSTRAINT "PK_V_MONEDA"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "IDPROVEEDOR"in table 'V_PROVEEDOR'
ALTER TABLE "ACTIVOS"."V_PROVEEDOR"
ADD CONSTRAINT "PK_V_PROVEEDOR"
   PRIMARY KEY ("IDPROVEEDOR" )
   ENABLE
   VALIDATE;


-- Creating primary key on "IDDOCUMENTO"in table 'V_TIPO_CAMBIO'
ALTER TABLE "ACTIVOS"."V_TIPO_CAMBIO"
ADD CONSTRAINT "PK_V_TIPO_CAMBIO"
   PRIMARY KEY ("IDDOCUMENTO" )
   ENABLE
   VALIDATE;


-- Creating primary key on "Id"in table 'CENTROS_DE_COSTOS'
ALTER TABLE "ACTIVOS"."CENTROS_DE_COSTOS"
ADD CONSTRAINT "PK_CENTROS_DE_COSTOS"
   PRIMARY KEY ("Id" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TIPOS_TRANSACCIONES'
ALTER TABLE "ACTIVOS"."TIPOS_TRANSACCIONES"
ADD CONSTRAINT "PK_TIPOS_TRANSACCIONES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TRANSACCIONES'
ALTER TABLE "ACTIVOS"."TRANSACCIONES"
ADD CONSTRAINT "PK_TRANSACCIONES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "Id"in table 'ActivosUsers'
ALTER TABLE "ACTIVOS"."ActivosUsers"
ADD CONSTRAINT "PK_ActivosUsers"
   PRIMARY KEY ("Id" )
   ENABLE
   VALIDATE;


-- Creating primary key on "COURSES"in table 'V_COURSES'
ALTER TABLE "ACTIVOS"."V_COURSES"
ADD CONSTRAINT "PK_V_COURSES"
   PRIMARY KEY ("COURSES" )
   ENABLE
   VALIDATE;


-- Creating primary key on "IDEMPLEADO"in table 'V_EMPLEADOS'
ALTER TABLE "ACTIVOS"."V_EMPLEADOS"
ADD CONSTRAINT "PK_V_EMPLEADOS"
   PRIMARY KEY ("IDEMPLEADO" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ACTIVOes_ID", "PRESTAMOes_ID"in table 'ACTIVOPRESTAMO'
ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO"
ADD CONSTRAINT "PK_ACTIVOPRESTAMO"
   PRIMARY KEY ("ACTIVOes_ID", "PRESTAMOes_ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "ID_PRESTAMO" in table 'EQUIPO_SOLICITADO'
ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO"
ADD CONSTRAINT "FK_A_PRESTAMOS"
   FOREIGN KEY ("ID_PRESTAMO")
   REFERENCES "ACTIVOS"."PRESTAMOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_A_PRESTAMOS'
CREATE INDEX "IX_FK_A_PRESTAMOS"
ON "ACTIVOS"."EQUIPO_SOLICITADO"
   ("ID_PRESTAMO");

-- Creating foreign key on "ACTIVOes_ID" in table 'ACTIVOPRESTAMO'
ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO"
ADD CONSTRAINT "FK_ACTIVOPRESTAMO_ACTIVO"
   FOREIGN KEY ("ACTIVOes_ID")
   REFERENCES "ACTIVOS"."ACTIVOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_ACTIVOPRESTAMO_ACTIVO'
CREATE INDEX "IX_FK_ACTIVOPRESTAMO_ACTIVO"
ON "ACTIVOS"."ACTIVOPRESTAMO"
   ("ACTIVOes_ID");

-- Creating foreign key on "PRESTAMOes_ID" in table 'ACTIVOPRESTAMO'
ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO"
ADD CONSTRAINT "FK_ACTIVOPRESTAMO_PRESTAMO"
   FOREIGN KEY ("PRESTAMOes_ID")
   REFERENCES "ACTIVOS"."PRESTAMOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_ACTIVOPRESTAMO_PRESTAMO'
CREATE INDEX "IX_FK_ACTIVOPRESTAMO_PRESTAMO"
ON "ACTIVOS"."ACTIVOPRESTAMO"
   ("PRESTAMOes_ID");

-- Creating foreign key on "TIPO_ACTIVOID" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_TIPO_ACTIVOACTIVO"
   FOREIGN KEY ("TIPO_ACTIVOID")
   REFERENCES "ACTIVOS"."TIPOS_ACTIVOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_TIPO_ACTIVOACTIVO'
CREATE INDEX "IX_FK_TIPO_ACTIVOACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("TIPO_ACTIVOID");

-- Creating foreign key on "TIPOS_ACTIVOSID" in table 'EQUIPO_SOLICITADO'
ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO"
ADD CONSTRAINT "FK_TIPOS_ACTIVOSEQUIPO_SOLICITADO"
   FOREIGN KEY ("TIPOS_ACTIVOSID")
   REFERENCES "ACTIVOS"."TIPOS_ACTIVOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_TIPOS_ACTIVOSEQUIPO_SOLICITADO'
CREATE INDEX "IX_FK_TIPOS_ACTIVOSEQUIPO_SOLICITADO"
ON "ACTIVOS"."EQUIPO_SOLICITADO"
   ("TIPOS_ACTIVOSID");

-- Creating foreign key on "ESTADO_ACTIVOID" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_ESTADO_ACTIVOACTIVO"
   FOREIGN KEY ("ESTADO_ACTIVOID")
   REFERENCES "ACTIVOS"."ESTADOS_ACTIVOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_ESTADO_ACTIVOACTIVO'
CREATE INDEX "IX_FK_ESTADO_ACTIVOACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("ESTADO_ACTIVOID");

-- Creating foreign key on "V_MONEDAID" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_V_MONEDAACTIVO"
   FOREIGN KEY ("V_MONEDAID")
   REFERENCES "ACTIVOS"."V_MONEDA"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_MONEDAACTIVO'
CREATE INDEX "IX_FK_V_MONEDAACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("V_MONEDAID");

-- Creating foreign key on "CENTRO_DE_COSTOId" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_CENTRO_DE_COSTOACTIVO"
   FOREIGN KEY ("CENTRO_DE_COSTOId")
   REFERENCES "ACTIVOS"."CENTROS_DE_COSTOS"
       ("Id")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_CENTRO_DE_COSTOACTIVO'
CREATE INDEX "IX_FK_CENTRO_DE_COSTOACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("CENTRO_DE_COSTOId");

-- Creating foreign key on "V_PROVEEDORIDPROVEEDOR" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_V_PROVEEDORACTIVO"
   FOREIGN KEY ("V_PROVEEDORIDPROVEEDOR")
   REFERENCES "ACTIVOS"."V_PROVEEDOR"
       ("IDPROVEEDOR")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_PROVEEDORACTIVO'
CREATE INDEX "IX_FK_V_PROVEEDORACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("V_PROVEEDORIDPROVEEDOR");

-- Creating foreign key on "V_ANFITRIONAID" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_V_ANFITRIONAACTIVO"
   FOREIGN KEY ("V_ANFITRIONAID")
   REFERENCES "ACTIVOS"."V_ANFITRIONA"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_ANFITRIONAACTIVO'
CREATE INDEX "IX_FK_V_ANFITRIONAACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("V_ANFITRIONAID");

-- Creating foreign key on "TIPO_TRANSACCIONID" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_TIPO_TRANSACCIONACTIVO"
   FOREIGN KEY ("TIPO_TRANSACCIONID")
   REFERENCES "ACTIVOS"."TIPOS_TRANSACCIONES"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_TIPO_TRANSACCIONACTIVO'
CREATE INDEX "IX_FK_TIPO_TRANSACCIONACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("TIPO_TRANSACCIONID");

-- Creating foreign key on "ACTIVOID" in table 'TRANSACCIONES'
ALTER TABLE "ACTIVOS"."TRANSACCIONES"
ADD CONSTRAINT "FK_ACTIVOTRANSACCION"
   FOREIGN KEY ("ACTIVOID")
   REFERENCES "ACTIVOS"."ACTIVOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_ACTIVOTRANSACCION'
CREATE INDEX "IX_FK_ACTIVOTRANSACCION"
ON "ACTIVOS"."TRANSACCIONES"
   ("ACTIVOID");

-- Creating foreign key on "V_ESTACIONID" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_V_ESTACIONACTIVO"
   FOREIGN KEY ("V_ESTACIONID")
   REFERENCES "ACTIVOS"."V_ESTACION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_ESTACIONACTIVO'
CREATE INDEX "IX_FK_V_ESTACIONACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("V_ESTACIONID");

-- Creating foreign key on "USUARIO_SOLICITA" in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "FK_ActivosUserPRESTAMO"
   FOREIGN KEY ("USUARIO_SOLICITA")
   REFERENCES "ACTIVOS"."ActivosUsers"
       ("Id")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_ActivosUserPRESTAMO'
CREATE INDEX "IX_FK_ActivosUserPRESTAMO"
ON "ACTIVOS"."PRESTAMOS"
   ("USUARIO_SOLICITA");

-- Creating foreign key on "USUARIO_APRUEBA" in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "FK_ActivosUserPRESTAMO1"
   FOREIGN KEY ("USUARIO_APRUEBA")
   REFERENCES "ACTIVOS"."ActivosUsers"
       ("Id")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_ActivosUserPRESTAMO1'
CREATE INDEX "IX_FK_ActivosUserPRESTAMO1"
ON "ACTIVOS"."PRESTAMOS"
   ("USUARIO_APRUEBA");

-- Creating foreign key on "V_EMPLEADOSIDEMPLEADO" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_V_EMPLEADOSACTIVO"
   FOREIGN KEY ("V_EMPLEADOSIDEMPLEADO")
   REFERENCES "ACTIVOS"."V_EMPLEADOS"
       ("IDEMPLEADO")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_EMPLEADOSACTIVO'
CREATE INDEX "IX_FK_V_EMPLEADOSACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("V_EMPLEADOSIDEMPLEADO");

-- Creating foreign key on "V_EMPLEADOSIDEMPLEADO" in table 'TRANSACCIONES'
ALTER TABLE "ACTIVOS"."TRANSACCIONES"
ADD CONSTRAINT "FK_V_EMPLEADOSTRANSACCION"
   FOREIGN KEY ("V_EMPLEADOSIDEMPLEADO")
   REFERENCES "ACTIVOS"."V_EMPLEADOS"
       ("IDEMPLEADO")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_V_EMPLEADOSTRANSACCION'
CREATE INDEX "IX_FK_V_EMPLEADOSTRANSACCION"
ON "ACTIVOS"."TRANSACCIONES"
   ("V_EMPLEADOSIDEMPLEADO");

-- Creating foreign key on "V_COURSESCOURSES" in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "FK_PRESTAMOV_COURSES"
   FOREIGN KEY ("V_COURSESCOURSES")
   REFERENCES "ACTIVOS"."V_COURSES"
       ("COURSES")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_PRESTAMOV_COURSES'
CREATE INDEX "IX_FK_PRESTAMOV_COURSES"
ON "ACTIVOS"."PRESTAMOS"
   ("V_COURSESCOURSES");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
