//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class V_PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public V_PROVEEDOR()
        {
            this.ACTIVOes = new HashSet<ACTIVO>();
        }
    
        public string IDPROVEEDOR { get; set; }
        public System.DateTime FECHAINGRESO { get; set; }
        [Display(Name="Proveedor")]
        public string NOMBRE { get; set; }
        public string RAZONSOCIAL { get; set; }
        public bool ESTADO { get; set; }
        public Nullable<int> TIPOCEDULA { get; set; }
        public string CEDULA { get; set; }
        public string TELEFONO { get; set; }
        public string FAX { get; set; }
        public string SITIOWEB { get; set; }
        public string CORREOELECTRONICO { get; set; }
        public bool LOCACION { get; set; }
        public string IDPAIS { get; set; }
        public string IDPROVINCIA { get; set; }
        public string DIRECCION { get; set; }
        public string IDFORMAPAGO { get; set; }
        public string IDPLAZO { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> INTERESMORA { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<bool> CONGELAR { get; set; }
        public System.DateTime CREADO { get; set; }
        public string CREADOR { get; set; }
        public System.DateTime MODIFICADO { get; set; }
        public string MODIFICADOR { get; set; }
        public string MONEDA { get; set; }
        public string NOMBRE_CORTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVO> ACTIVOes { get; set; }
    }
}
